ratio = None
# Content for the 5 additional format-prototype tabs.
# Every prompt/question traces to the episode's real n-gram table; every entity to the matching-scope entity map.

TOPICS = [
{
 "tab": "Truck Accidents (GA)",
 "emoji": "\U0001F69B",
 "title": "Why Truck Accident Cases Are Worth More Than Car Cases, and Harder to Win",
 "practice_area": "Truck Accidents",
 "scope_label": "GA - Savannah",
 "runtime": "~47 minutes (Interview ~25 min, Location Blocks ~15 min, Intro/Close ~7 min)",
 "ngram": "podcast/N-Gram Tables/Truck Accidents/Why Truck Accident Cases Are Worth More Than Car Cases - and Harder to Win/Locations/GA - Savannah/n-gram-table.json",
 "emap": "podcast-research/truck-accidents/ga-savannah/01-entities/entity-map.json",
 "jurisdiction": "Georgia is a modified comparative negligence state with a 50% bar ([O.C.G.A. Section 51-12-33]{.underline}). Statute of limitations is 2 years for personal injury ([O.C.G.A. Section 9-3-33]{.underline}); wrongful death priority runs spouse, then children, then parents ([O.C.G.A. Section 51-4-2]{.underline}). Punitive damages are capped at $250K with a DUI exception ([O.C.G.A. Section 51-12-5.1]{.underline}). Georgia adopted Daubert in 2005 ([O.C.G.A. Section 24-7-702]{.underline}), which matters because these cases are expert-driven. Commercial carriers carry a federal coverage floor via the [MCS-90 Endorsement]{.underline} and typically stack primary plus umbrella. Venue options are [Chatham County State Court]{.underline}, [Chatham County Superior Court]{.underline}, and the [U.S. District Court for the Southern District of Georgia, Savannah Division]{.underline}.",
 "intro": "today I want to get into why a wreck with an 18-wheeler is a completely different animal from a wreck with a car, even when the crash looks the same on paper.",
 "framing": "Roughly: same intersection, same speed, two completely different cases. One is an insurance claim. The other is litigation against a company with a rapid response team that was on the phone before the ambulance left.",
 "prompts": [
  {"t":"Two crashes, two different worlds","q":"Take two wrecks at the same intersection, same speed. One is a sedan, one is an 18-wheeler. From your side of the desk, what actually makes those two different cases?",
   "g":["Weight and physics: a [Semi-trailer truck / 18-wheeler]{.underline} at 80,000 pounds against a passenger vehicle","[Catastrophic Injury]{.underline} as the default outcome rather than the exception","A company on the other side instead of an individual driver","Federal regulation applies to one and not the other"],
   "f":["When you get the call, what tells you immediately this is a truck case and not a car case?","Does the other side behave differently from hour one?"]},
  {"t":"Who is actually on the other side","q":"When you sue over a truck wreck, who is actually the defendant? Because I get the sense it is rarely just the driver.",
   "g":["[Trucking Company / Motor Carrier Liability]{.underline} through respondeat superior","[Negligent Hiring / Retention / Supervision]{.underline} under [Daniel v. Bremen-Bowdon Investment Co.]{.underline}","[Negligent Entrustment]{.underline} under [Western Indus. v. Poole]{.underline}","[Broker Liability]{.underline} and the [Miller v. C.H. Robinson]{.underline} preemption split","[Shipper / Cargo-Loader Liability]{.underline} and [Maintenance / Repair Contractor Liability]{.underline}"],
   "f":["How many defendants is normal in one of these?","Does adding the company change what you can actually recover, or just who writes the check?"]},
  {"t":"The race for evidence","q":"I have heard the evidence in these cases starts disappearing almost immediately. Is that real, or is that a lawyer telling a good story?",
   "g":["[Spoliation / Preservation Letter]{.underline} as the first move, often within days","[Truck Black Box / Event Data Recorder / Engine Control Module (ECM)]{.underline} overwrite cycles","[Electronic Logging Device (ELD) Data]{.underline} under [49 CFR Section 395.20]{.underline}","[Telematics / GPS Fleet Data]{.underline} and [Truck Dashcam / Forward-Facing Camera Footage]{.underline}","The carrier's own rapid response team arriving before anyone calls a lawyer"],
   "f":["How fast is fast? Days? Hours?","What happens if that letter never goes out?","Have you had one where the data was already gone?"]},
  {"t":"The federal rulebook","q":"There is a whole body of federal regulation that applies to a trucking company and does not apply to me in my car. What does that actually give you?",
   "g":["[Federal Motor Carrier Safety Administration (FMCSA)]{.underline} and [FMCSA Regulations (49 CFR Parts 350-399)]{.underline}","[Hours of Service Rules (49 CFR Part 395)]{.underline} and what the logs show","[Commercial Driver's License (CDL, 49 CFR Part 383)]{.underline} qualification files","Post-accident drug and alcohol testing records","A violated federal rule as a liability shortcut rather than a jury argument about reasonableness"],
   "f":["Is a rule violation basically automatic liability, or is it more complicated?","Which of these regulations produces the most cases?"]},
  {"t":"Why the money is different","q":"People hear truck case and assume big number. Where does that number actually come from, and is the assumption fair?",
   "g":["[MCS-90 Endorsement]{.underline} federal floor and the [Primary + Umbrella / Excess Coverage Stack]{.underline}","[Life Care Plan]{.underline} built by a CLCP for catastrophic injury","[Economic Loss / Vocational Rehabilitation Expert]{.underline} on lost capacity","Non-economic damages when the injury is permanent","[O.C.G.A. Section 51-12-5.1]{.underline} punitive damages and the DUI exception to the $250K cap"],
   "f":["Does a bigger policy actually mean a bigger recovery, or just a longer fight?","When do punitives realistically come into play?"],
   "story": True},
  {"t":"Why they are harder to win","q":"The episode title says these are worth more and harder to win. Make the second half of that case for me.",
   "g":["[Qualified Expert Testimony]{.underline} and the [Daubert standard]{.underline} under [O.C.G.A. Section 24-7-702]{.underline}","[Accident Reconstructionist (PE / ACTAR)]{.underline} and the cost of building the case","[Corporate Representative Deposition]{.underline} under [O.C.G.A. Section 9-11-30(b)(6)]{.underline}","[O.C.G.A. Section 51-12-33]{.underline} and the 50% bar as the defense's main lever","[Federal Diversity Removal]{.underline} and what changes when the case moves"],
   "f":["What is the defense trying hardest to prove?","How much does one of these cost to actually take to trial?"]},
 ],
 "blocks": [
  {"city":"Savannah","qs":[
   {"q":"Who investigates a commercial truck crash in Savannah?","b":["[Savannah Police Department (SPD)]{.underline} Traffic Investigation Unit inside city limits","[Georgia State Patrol]{.underline} Specialized Collision Reconstruction Team, Post 42 Rincon, for the Savannah region","What the report establishes and what still has to be proven independently"]},
   {"q":"Which court hears a Savannah truck accident lawsuit?","b":["[Chatham County State Court]{.underline} as the standard civil tort venue","[Chatham County Superior Court]{.underline} for general jurisdiction matters","[U.S. District Court, Southern District of Georgia, Savannah Division]{.underline} after [Federal Diversity Removal]{.underline}"]},
   {"q":"Where do serious truck crash victims go for trauma care in Savannah?","b":["[Memorial Health University Medical Center]{.underline}, the Level I trauma center for southeast Georgia","[St. Joseph's/Candler Health System]{.underline} as secondary trauma reception","Why the treatment record starts building the damages case on day one"]},
   {"q":"How long do you have to file a truck accident lawsuit in Georgia?","b":["Two years for personal injury under [O.C.G.A. Section 9-3-33]{.underline}","Wrongful death priority under [O.C.G.A. Section 51-4-2]{.underline}","Why waiting is worse here than in a car case, because the evidence is on a shorter clock than the statute"]},
   {"q":"Why are I-95 and I-16 such high-risk corridors around Savannah?","b":["[I-95 / I-16 corridor]{.underline} as the region's two commercial truck arteries","[Jackknife / Rollover]{.underline} dynamics from I-95 coastal wind and I-16 rural curves","[Georgia Department of Transportation]{.underline} District 5 covering Chatham County"]},
   {"q":"How does Georgia's 50 percent bar affect a Savannah truck case?","b":["[O.C.G.A. Section 51-12-33]{.underline} modified comparative negligence and the hard cutoff at 50 percent","Recovery reduced by fault share below the bar, eliminated at or above it","Why the defense invests so heavily in moving the plaintiff a few percentage points"]},
  ]},
  {"city":"Garden City and the Port corridor","qs":[
   {"q":"How is a Port of Savannah drayage crash different from an over-the-road truck crash?","b":["[Port of Savannah / Garden City Terminal]{.underline} as a top-four US container port generating dense short-haul traffic","[Port drayage / chassis liability]{.underline} spreading exposure across shipper, motor carrier, and chassis pool","Why the defendant list is longer and the equipment ownership question comes first"]},
   {"q":"Who is liable when the cargo or the chassis caused the Garden City crash?","b":["[Shipper / Cargo-Loader Liability]{.underline} for securement under [49 CFR Part 393 Subpart I]{.underline}","[Maintenance / Repair Contractor Liability]{.underline} under [49 CFR Part 393]{.underline}","Intermodal equipment and why nobody wants to own the chassis"]},
   {"q":"Who responds to a truck crash in Chatham County outside Savannah city limits?","b":["[Chatham County Sheriff's Office / Chatham County Police]{.underline} for county jurisdiction","[Georgia State Patrol]{.underline} Post 42 Rincon for reconstruction","Why jurisdiction determines which report exists and how fast you get it"]},
   {"q":"What is an underride collision and why does it matter near the port?","b":["[Underride Collision]{.underline}, rear and side, and the role of the DOT bar or Mansfield bar","Why the injury pattern is disproportionately catastrophic","How equipment condition becomes its own liability theory"]},
   {"q":"What happens when a hazmat load is involved in a Garden City crash?","b":["[Hazmat / Hazardous Materials Carriers]{.underline} under [49 CFR Section 177]{.underline}","Additional federal duties and additional records","Why the regulatory file gets larger and more useful"]},
   {"q":"What should someone do in the first days after being hit by a truck near the port?","b":["Get a [Spoliation / Preservation Letter]{.underline} out before the ECM data cycles","Treat at [Memorial Health University Medical Center]{.underline} and keep the record continuous","Say nothing recorded to the [Commercial Insurance Adjuster]{.underline}"]},
  ]},
 ],
 "closing_q": "If somebody listening got hit by a truck last week and has not called anyone yet, what is the one thing you want them to do today?",
},

{
 "tab": "Birth Injury (MD)",
 "emoji": "\U0001F476",
 "title": "Cerebral Palsy and HIE: What Happened, and Was It Preventable",
 "practice_area": "Birth Injury",
 "scope_label": "MD - Baltimore City",
 "runtime": "~48 minutes (Interview ~25 min, Location Blocks ~15 min, Intro/Close ~8 min)",
 "ngram": "podcast/N-Gram Tables/Birth Injury/E09 - Cerebral Palsy and HIE - What Happened, and Was It Preventable/Locations/Baltimore City/n-gram-table.json",
 "emap": "podcast-research/birth-injury/md/01-entities/entity-map.json",
 "jurisdiction": "Maryland is one of the few remaining [Maryland Contributory Negligence Rule]{.underline} states, which makes causation unusually decisive. Every medical negligence claim begins at the [Health Care Alternative Dispute Resolution Office (HCADRO)]{.underline} rather than in court, and requires a [Certificate of Qualified Expert]{.underline} under [Cts. & Jud. Proc. 3-2A-04(b)]{.underline}. The [Maryland Minor Tolling Rule for Birth Injury]{.underline} under [Section 5-109(d)]{.underline} changes what too late means for a child. Non-economic damages are capped under [Cts. & Jud. Proc. Section 3-2A-09]{.underline}. Venue is the [Circuit Court for Baltimore City]{.underline} or the [Circuit Court for Montgomery County]{.underline}. TONE NOTE: this is the most emotionally loaded topic in the library. Slow the interview down. Do not chase a story from a parent's perspective.",
 "intro": "today we are talking about cerebral palsy and HIE, and specifically the question every parent eventually asks, which is whether this could have been prevented.",
 "framing": "Roughly: a diagnosis explains what is happening but it does not explain why. Some of these are nobody's fault. Some are not. This episode is about how a family finds out which one they are in.",
 "prompts": [
  {"t":"The day they hear the words","q":"When a parent hears the words cerebral palsy for the first time, what does that diagnosis actually tell them, and what does it not tell them yet?",
   "g":["[Cerebral Palsy]{.underline} as a description of the effect, not an explanation of the cause","[Neonatal Brain Damage]{.underline} and [Developmental Delay]{.underline} as the observable pieces","Type and severity vary enormously, and early prognosis is unreliable","What the diagnosis says about timing, which is very little on its own"],
   "f":["What do parents usually assume the diagnosis means?","What is the first thing you tell a family that calls you the week they heard it?"]},
  {"t":"Not everything is malpractice","q":"Cerebral palsy is not always anyone's fault. How do you have that conversation honestly with a family that is looking for an answer?",
   "g":["[Birth Defects]{.underline} versus birth injury and why the distinction matters so much","Genetic, infectious, and developmental causes that are nobody's fault","The honest first step: get the [Labor and Delivery Medical Records]{.underline} and the [Fetal Monitoring Strips]{.underline}","Reviewing a case is not the same as filing one"],
   "f":["How often does a case you review turn out to be nobody's fault?","How do you tell a family that?"],
   "story": True},
  {"t":"What oxygen loss actually does","q":"Walk me through what is physically happening when a baby loses oxygen during labor, and how that becomes a permanent injury.",
   "g":["[Birth Asphyxia (Oxygen Deprivation)]{.underline} and [Hypoxic-Ischemic Encephalopathy (HIE)]{.underline}","[Umbilical Cord Prolapse and Compression]{.underline} and [Placental Abruption]{.underline} as mechanisms","How quickly it becomes an emergency","Why the duration question is the most contested fact in the entire case"],
   "f":["How much time is too much time?","Is that a number people agree on, or is that itself the fight?"]},
  {"t":"The chart tells on itself","q":"How does anyone reconstruct what happened in a delivery room years after the fact?",
   "g":["[Fetal Monitoring Strips]{.underline}, [Electronic Fetal Monitoring (EFM)]{.underline}, and the [Category III Tracing]{.underline}","[APGAR Score]{.underline} and [Umbilical Cord Blood Gas Analysis]{.underline} from the first minutes","[Placental Pathology Report]{.underline} and what it adds","[Therapeutic Hypothermia]{.underline} as a tell: cooling means the team suspected HIE at the time"],
   "f":["If a baby was cooled, what does that tell you as a lawyer?","What records should a family request, and from whom?"]},
  {"t":"Breach is the easy part","q":"I have heard lawyers say breach is the easier half and causation is the war. What does that actually mean for a family trying to understand their own case?",
   "g":["[Standard of Care]{.underline} and [ACOG Practice Guidelines]{.underline} as the measuring stick","[Breach of the Standard of Care]{.underline} versus [Causation (Proximate Cause)]{.underline}","[Delayed Emergency Cesarean Section]{.underline} and how much the timing of the decision matters","[Forceps and Vacuum Extraction Injury]{.underline} and where a judgment call becomes a departure","Why [Maryland Contributory Negligence Rule]{.underline} raises the stakes on every causation question"],
   "f":["Can you prove someone did something wrong and still lose?","What convinces you a case is real?"]},
  {"t":"A lifetime, priced out","q":"What does a family actually end up paying for over a lifetime, and how does anyone put a number on that?",
   "g":["[Life Care Plan]{.underline} covering therapy hours, equipment, home modification, attendant care","[Future Medical Expenses]{.underline} and [Lost Earning Capacity]{.underline}","[Maryland Noneconomic Damages Cap]{.underline} and what it does and does not limit","[Maryland Special Needs Trust and ABLE Account]{.underline} protecting a recovery for decades"],
   "f":["What surprises families most about the real cost?","How do you protect money for a child who will need it at forty?"]},
 ],
 "blocks": [
  {"city":"Baltimore City","qs":[
   {"q":"Where are birth injuries treated in Baltimore?","b":["[The Johns Hopkins Hospital]{.underline} and [University of Maryland Medical Center]{.underline} as the higher-level NICUs","[Kennedy Krieger Institute]{.underline} for pediatric neurodevelopmental evaluation","Why a transfer between Baltimore hospitals is itself a documented event with a timestamp"]},
   {"q":"What is therapeutic hypothermia and why does the Baltimore transfer window matter?","b":["[Therapeutic Hypothermia (Head and Body Cooling)]{.underline} must begin inside a narrow window after birth","Transfer to a higher-level [Neonatal Intensive Care Unit (NICU)]{.underline} is often required","A missed window becomes both a damages issue and a liability issue"]},
   {"q":"Which court hears a Baltimore City birth injury case?","b":["[Circuit Court for Baltimore City]{.underline} after the HCADRO step","Why venue matters less than most families expect","What the timeline realistically looks like"]},
   {"q":"What is HCADRO and why does every Maryland claim start there?","b":["[Health Care Alternative Dispute Resolution Office (HCADRO)]{.underline} under the [Maryland Health Care Malpractice Claims Act]{.underline}","What the step requires and what it adds to the calendar","Why cases end here without a [Certificate of Qualified Expert]{.underline}"]},
   {"q":"How long does a family in Baltimore have to file a birth injury claim?","b":["[Maryland Statute of Limitations for Medical Injury]{.underline} under [Cts. & Jud. Proc. 5-109]{.underline}","[Maryland Minor Tolling Rule for Birth Injury]{.underline} under [Section 5-109(d)]{.underline} and how it changes the deadline for a child","Why waiting still costs a family even when the deadline has not run"]},
   {"q":"What should a Baltimore family request from the hospital first?","b":["[Labor and Delivery Medical Records]{.underline} and the complete [Fetal Monitoring Strips]{.underline}","The [Placental Pathology Report]{.underline}, which families rarely know exists","How to request them and what it costs, which is usually nothing"]},
  ]},
  {"city":"Montgomery County and Silver Spring","qs":[
   {"q":"Where are birth injuries treated in Montgomery County?","b":["[Holy Cross Hospital]{.underline} in Silver Spring as the primary local delivery volume","Transfer patterns into Baltimore or [MedStar Washington Hospital Center]{.underline} for higher-level NICU care","Why the transfer decision and its timing become part of the record"]},
   {"q":"Does a Montgomery County case run differently from a Baltimore City case?","b":["[Circuit Court for Montgomery County]{.underline} as venue","Same [HCADRO]{.underline} entry point and same [Certificate of Qualified Expert]{.underline} requirement","What actually differs, which is jury pool and pace rather than law"]},
   {"q":"Does the standard of care change between a large teaching hospital and a community hospital?","b":["[Standard of Care]{.underline} measured against [ACOG Practice Guidelines]{.underline}, not against the hospital's size","What a smaller hospital is expected to recognize and when it is expected to transfer","[Obstetrician (OB/GYN)]{.underline} and [Labor and Delivery Nurse]{.underline} duties running in parallel"]},
   {"q":"What happens if a family lives in Montgomery County but delivered in DC?","b":["[Superior Court of the District of Columbia]{.underline} as an alternate venue","[District of Columbia Medical Malpractice Pre-Suit Notice]{.underline} under [D.C. Code Section 16-2802]{.underline}","Why the delivery location, not the home address, usually drives the analysis"]},
   {"q":"Who regulates the physicians involved in a Maryland birth injury?","b":["[Maryland Board of Physicians]{.underline} and what a complaint does and does not accomplish","Why a board complaint is not a substitute for a claim","How the two tracks interact"]},
   {"q":"What does it cost a Montgomery County family to have a case reviewed?","b":["[Contingency Fee]{.underline} structure and what the first conversation involves","Who pays for the expert review, which is the firm","What a family should expect to walk away knowing"]},
  ]},
 ],
 "closing_q": "For a parent listening right now whose child was recently diagnosed and who has no idea whether any of this applies to them, what would you tell them?",
},

{
 "tab": "Medical Malpractice (FL)",
 "emoji": "\U0001F3E5",
 "title": "The Hospital Is the Real Defendant",
 "practice_area": "Medical Malpractice",
 "scope_label": "FL - Boca Raton",
 "runtime": "~47 minutes (Interview ~25 min, Location Blocks ~15 min, Intro/Close ~7 min)",
 "ngram": "podcast/N-Gram Tables/Medical Malpractice/The Hospital Is the Real Defendant/Locations/FL - Boca Raton/n-gram-table.json",
 "emap": "podcast-research/medical-malpractice/fl-boca-raton/01-entities/entity-map.json",
 "jurisdiction": "Florida requires a full pre-suit process under [FS Chapter 766]{.underline}, including a [Notice of Intent and 90-day investigation]{.underline} under [FS 766.106]{.underline} and a [Corroborating Affidavit]{.underline} under [FS 766.203]{.underline}. The same-specialty expert requirement under [FS 766.102]{.underline} shapes who can even opine. There is no cap on non-economic damages after [North Broward Hosp. Dist. v. Kalitan]{.underline} (Fla. 2017). The clock is 2 years from discovery with a 4-year repose under [FS 95.11(5)(c)]{.underline}. Public hospitals carry [sovereign immunity caps]{.underline} under [FS 768.28]{.underline}. Venue is the [Palm Beach County Civil Courthouse]{.underline}, 15th Judicial Circuit.",
 "intro": "today I want to talk about something most people get wrong from the very first phone call, which is who they are actually suing when a hospital hurts them.",
 "framing": "Roughly: people come in wanting to sue the doctor. Very often the doctor is not the one with the money, is not the one who set the conditions, and is not even technically an employee of the building you were standing in.",
 "prompts": [
  {"t":"The assumption everyone walks in with","q":"Somebody gets hurt at a hospital and calls you. Who do they think they are suing, and who are they actually suing?",
   "g":["[Hospital / Health System]{.underline} as the institutional defendant versus the individual provider","[Independent-Contractor Physician]{.underline} and the ER staffing model most patients have never heard of","[ER Physician Staffing Company]{.underline} sitting between the doctor and the building","Why the badge, the signage, and the bill all say the same name and none of it means employment"],
   "f":["Do patients ever know their ER doctor was not a hospital employee?","When do you find out, and how?"]},
  {"t":"Pulling the hospital back in","q":"If the doctor is technically a contractor, how does the hospital end up on the hook anyway?",
   "g":["[Apparent Agency / Ostensible Agency]{.underline} and what a reasonable patient believed","[Vicarious Liability]{.underline} and [Respondeat Superior]{.underline} for [Nurses and Hospital Staff]{.underline}","[Corporate Negligence]{.underline} as a claim against the institution itself","[Negligent Credentialing]{.underline} for who the hospital allowed to practice there"],
   "f":["Which of those is the strongest in practice?","Does the hospital fight the agency question hard?"]},
  {"t":"The system, not the person","q":"What is the difference between one provider making one mistake and the hospital itself being negligent?",
   "g":["[Corporate Negligence]{.underline} versus an individual departure from the [Standard of Care]{.underline}","[ER Understaffing and Triage Failure]{.underline} as a systemic condition","[Delayed Treatment / Failure to Monitor]{.underline} as a pattern rather than an event","Why policies and staffing grids become exhibits"],
   "f":["How do you prove a system failed rather than a person?","What does the hospital say in response?"]},
  {"t":"Where the money actually is","q":"Why does it matter so much whether the negligent doctor was underinsured?",
   "g":["[Underinsured Defendant Physician]{.underline} and Florida's thin physician coverage reality","[Medical Malpractice Insurance / Policy Layers]{.underline} and how they stack","[Hospital Self-Insurance and Captive Layers]{.underline} as where catastrophic cases actually get funded","Why the viable defendant and the culpable defendant are not always the same person"],
   "f":["Is that uncomfortable to explain to a client?","Do you ever have a real case and no way to fund it?"],
   "story": True},
  {"t":"The paper trail","q":"What actually proves what happened in a hospital, years later?",
   "g":["[Medical Records, Charts and Hospital Policies]{.underline} as the backbone","[Nurse Charting / EMR Timestamps]{.underline} and what the metadata reveals about sequence","[Hospital Incident Reports]{.underline} and the fight over producing them","[Spoliation of Evidence]{.underline} and how you stop a record from moving"],
   "f":["Do timestamps ever contradict the narrative in the chart?","What is the first record you ask for?"]},
  {"t":"Florida's gauntlet","q":"Florida makes you do a lot before you are allowed to file. Walk me through what a family is signing up for.",
   "g":["[Florida Medical Malpractice Pre-Suit Process (FS Chapter 766)]{.underline} start to finish","[Notice of Intent and the 90-day investigation]{.underline} under [FS 766.106]{.underline}","[Corroborating Affidavit / Affidavit of Merit]{.underline} under [FS 766.203]{.underline}","[Florida Same-Specialty Expert]{.underline} requirement under [FS 766.102]{.underline}","Why [Kalitan]{.underline} removing the non-economic cap matters on the other end"],
   "f":["How long is all of that, realistically?","How many cases die in pre-suit?"]},
 ],
 "blocks": [
  {"city":"Boca Raton","qs":[
   {"q":"Which hospitals serve Boca Raton and how does that affect a claim?","b":["[Boca Raton Regional Hospital]{.underline} within [Baptist Health South Florida]{.underline}","[West Boca Medical Center / Bethesda Hospital East]{.underline} within the same system","Why the parent system, not the building, often determines the real defendant"]},
   {"q":"Where do you file a Boca Raton medical malpractice case?","b":["[Palm Beach County Civil Courthouse]{.underline}, 15th Judicial Circuit","What has to be finished before you are allowed to file at all","Realistic timeline from first call to filing"]},
   {"q":"How long do you have to bring a hospital negligence claim in Florida?","b":["Two years from discovery under [FS 95.11(5)(c)]{.underline}","[Florida Statute of Repose]{.underline}: four-year outer bar, seven years for fraud, minor tolling to eight","Why the repose can end a claim before anyone knew there was one"]},
   {"q":"Is there a cap on pain and suffering in a Florida hospital case?","b":["No cap on non-economic damages after [Kalitan]{.underline} (Fla. 2017)","[Non-Economic Damages]{.underline} and [Economic Damages]{.underline} valued separately","[Future Medical and Life-Care Costs]{.underline} in catastrophic cases"]},
   {"q":"What kinds of ER mistakes become claims in Boca Raton?","b":["[Misdiagnosis / Failure to Diagnose]{.underline} as the dominant category","[ER Understaffing and Triage Failure]{.underline}","[Loss of Chance Doctrine]{.underline} and [Medical Causation]{.underline} deciding viability"]},
   {"q":"What is the first step if you suspect a Boca Raton hospital harmed your family?","b":["Request the complete record, including nursing notes and [EMR timestamps]{.underline}","Do not sign anything the hospital's risk management sends","Get it reviewed before the [FS 95.11]{.underline} clock does anything"]},
  ]},
  {"city":"Delray Beach and Palm Beach County","qs":[
   {"q":"Where do the most serious Palm Beach County cases get treated?","b":["[Delray Medical Center]{.underline} as the Level I trauma center for Palm Beach County","Why trauma transfer creates a second set of providers and a second set of records","How the handoff itself becomes a liability question"]},
   {"q":"How is suing a public hospital in Palm Beach County different?","b":["[Florida Sovereign Immunity / Public Hospital Caps]{.underline} under [FS 768.28]{.underline}","Different notice requirements and a hard ceiling on recovery","Why identifying the ownership structure is the very first research step"]},
   {"q":"Who regulates hospitals and physicians in Florida?","b":["[Florida Board of Medicine]{.underline} and the [Florida Department of Health]{.underline}","[Florida Agency for Health Care Administration (AHCA)]{.underline} for facility-level issues","What a regulatory complaint accomplishes, and what it does not"]},
   {"q":"What expert does Florida require in a Palm Beach County ER case?","b":["[Florida Same-Specialty Expert]{.underline} requirement under [FS 766.102]{.underline}","[Florida Daubert Expert Standard]{.underline} under [FS 90.702]{.underline}","Why the wrong specialty ends a case before it starts"]},
   {"q":"Can a hospital lose or alter records in a Palm Beach County case?","b":["[Spoliation of Evidence]{.underline} and the preservation demand","[Hospital Incident Reports]{.underline} and the privilege fight over them","[Res Ipsa Loquitur]{.underline} in the narrow cases where it still applies"]},
   {"q":"How are future life-care costs valued against a Palm Beach County hospital?","b":["[Future Medical and Life-Care Costs]{.underline} built by a planner","[Medical Expert Witness]{.underline} testimony supporting projection","[Hospital Self-Insurance and Captive Layers]{.underline} determining what is actually collectible"]},
  ]},
 ],
 "closing_q": "If someone listening thinks a hospital hurt someone in their family but they are not sure it rises to a case, what should they do this week?",
},

{
 "tab": "Brain Injury (TX)",
 "emoji": "\U0001F9E0",
 "title": "Understanding Traumatic Brain Injury Claims",
 "practice_area": "Traumatic Brain Injury",
 "scope_label": "TX - Fort Worth",
 "runtime": "~46 minutes (Interview ~25 min, Location Blocks ~14 min, Intro/Close ~7 min)",
 "ngram": "podcast/N-Gram Tables/Traumatic Brain Injury/E5 Understanding Traumatic Brain Injury Claims/Locations/TX - Fort Worth/n-gram-table.json",
 "emap": "podcast-research/traumatic-brain-injury/locations/tx-fort-worth/01-entities/entity-map.json",
 "jurisdiction": "Texas applies [51% modified comparative negligence]{.underline} under [Tex. CPRC Section 33.001]{.underline}, with a 2-year statute of limitations under [Tex. CPRC Section 16.003]{.underline} and a 6-month notice requirement for government defendants under the [Texas Tort Claims Act]{.underline}. Minimum auto liability is 30/60/25 under [Tex. Transp. Code Section 601]{.underline}, which is routinely inadequate in a serious brain injury case. Crash documentation runs through the [Texas Peace Officer's Crash Report / TxDOT CRIS (CR-3)]{.underline}. Venue is [Tarrant County District Court (Civil)]{.underline} or [Tarrant County Civil Court at Law]{.underline}, with appeals to the [Second Court of Appeals]{.underline} in Fort Worth.",
 "intro": "today we are talking about the injury that does not show up in a photograph, and why that one fact makes these cases harder than almost anything else we handle.",
 "framing": "Roughly: a broken leg proves itself. A brain injury has to be proven, over and over, to people who are actively looking for a reason not to believe it.",
 "prompts": [
  {"t":"The injury nobody can see","q":"With most injuries there is an X-ray and an argument is over. What makes a brain injury different from the moment the client walks in?",
   "g":["[Traumatic Brain Injury (TBI)]{.underline} and [Concussion / Mild TBI (mTBI)]{.underline} often invisible on standard imaging","[Diffuse Axonal Injury (DAI)]{.underline} and why it does not present like a [Subdural Hematoma]{.underline}","[Glasgow Coma Scale (GCS)]{.underline} at the scene and how a decent score early misleads everyone","The client often does not know something is wrong yet"],
   "f":["Does the client usually recognize it themselves?","Who notices first?"]},
  {"t":"What it actually does to a life","q":"Set the legal side aside for a second. What does a brain injury actually do to somebody's day to day life?",
   "g":["[Post-Concussion Syndrome (PCS)]{.underline} and the symptoms that do not resolve","Personality, memory, executive function, and the things that do not photograph","[Loss of Consortium]{.underline} and what happens to a marriage and a household","Why the family sees it before any doctor documents it"],
   "f":["What do spouses tell you that clients do not?","What is the thing clients are most embarrassed to admit?"],
   "story": True},
  {"t":"Proving it","q":"How do you actually prove an injury that does not show up on a standard scan?",
   "g":["[Neuroimaging (CT, MRI, DTI, fMRI)]{.underline} and what each modality can and cannot show","[Neuropsychological Testing]{.underline} as the objective backbone","[Fort Worth / Tarrant County Neurologist]{.underline} and the treating-physician record","[Causation (Proximate Cause)]{.underline} tied back to the [CR-3 crash report]{.underline}"],
   "f":["Which single piece of evidence moves an adjuster the most?","How early does the testing need to happen?"]},
  {"t":"How the other side fights it","q":"What is the insurance company's playbook against a brain injury claim?",
   "g":["[Independent Medical Examination (IME)]{.underline} and what it is actually for","Attacking [Causation]{.underline} through [pre-existing conditions]{.underline} and the [Eggshell Skull Doctrine]{.underline} response","Gaps in treatment used as proof nothing was wrong","[Texas 51% Modified Comparative Negligence]{.underline} as the lever on the liability side"],
   "f":["How should a client handle an IME?","What is the mistake that hands them the case?"]},
  {"t":"Pricing a life that changed","q":"How does anyone put a number on cognitive and emotional change?",
   "g":["[Life Care Plan]{.underline} and [Future Medical Expenses]{.underline} projected to [Maximum Medical Improvement (MMI)]{.underline} and beyond","[Loss of Earning Capacity]{.underline} where the person can still work but not at the same level","[Pain and Suffering]{.underline} for deficits with no receipt","[Insurance Policy Limits]{.underline} as the practical ceiling, especially against 30/60/25"],
   "f":["What is most often undervalued?","What happens when the policy is far smaller than the harm?"]},
  {"t":"The long tail","q":"These injuries do not stay static. How do you account for something that may get worse in twenty years?",
   "g":["[Chronic Traumatic Encephalopathy (CTE)]{.underline} and degenerative progression","Why settling before [MMI]{.underline} is a specific kind of mistake here","[Medical Lien]{.underline} resolution and protecting the net","[Texas 2-Year Statute of Limitations]{.underline} against a slow-emerging injury"],
   "f":["How do you advise someone who needs money now?","Can you ever go back?"]},
 ],
 "blocks": [
  {"city":"Fort Worth","qs":[
   {"q":"Where do serious brain injuries get treated in Fort Worth?","b":["[JPS Health Network]{.underline} (John Peter Smith Hospital), the Level I trauma center","[Texas Health Harris Methodist Hospital Fort Worth]{.underline}","[Cook Children's Medical Center]{.underline} for pediatric TBI"]},
   {"q":"Who documents a Fort Worth crash that causes a brain injury?","b":["[Fort Worth Police Department (FWPD)]{.underline} at the scene","[Texas Peace Officer's Crash Report / TxDOT CRIS (CR-3)]{.underline} as the underlying record","Why the CR-3 narrative matters more in a TBI case than in a typical crash"]},
   {"q":"How long do you have to file a brain injury claim in Texas?","b":["Two years under [Tex. CPRC Section 16.003]{.underline}","Six months notice for a government defendant under the [Texas Tort Claims Act]{.underline}","Why a slowly diagnosed injury runs into the deadline more often here"]},
   {"q":"How does Texas comparative fault threaten a Fort Worth brain injury claim?","b":["[Texas 51% Modified Comparative Negligence]{.underline} under [Tex. CPRC Section 33.001]{.underline}","At 51 percent the recovery is gone entirely, not reduced","Why the defense spends so much on the liability side of a damages case"]},
   {"q":"What happens when the at-fault driver only carries Texas minimums?","b":["[Texas Minimum Auto Liability 30/60/25]{.underline} under [Tex. Transp. Code Section 601]{.underline}","Why that number is meaningless against a [Life Care Plan]{.underline}","Finding every applicable policy before anyone talks settlement"]},
   {"q":"Why do I-35W and I-30 produce so many of these cases?","b":["[I-35W / I-30 Fort Worth Highway Collision]{.underline} patterns and speed differential","High-speed impact and [Diffuse Axonal Injury]{.underline}","Why freeway crashes disproportionately produce injuries that image poorly"]},
  ]},
  {"city":"Tarrant County","qs":[
   {"q":"Which Tarrant County court hears a brain injury lawsuit?","b":["[Tarrant County District Court (Civil)]{.underline} for larger claims","[Tarrant County Civil Court at Law]{.underline} depending on amount","[Second Court of Appeals]{.underline} in Fort Worth on appeal"]},
   {"q":"What does a Tarrant County neurologist add to a brain injury case?","b":["[Fort Worth / Tarrant County Neurologist]{.underline} as treating physician rather than hired expert","[Fort Worth / Tarrant County Treating Physician]{.underline} continuity as credibility","Why a local treating record outperforms a retained opinion"]},
   {"q":"How does neuropsychological testing work in a Tarrant County case?","b":["[Neuropsychological Testing]{.underline} producing objective deficit measurement","How it survives an [Independent Medical Examination]{.underline} challenge","Timing: baseline as early as possible"]},
   {"q":"What happens in a fatal Tarrant County brain injury case?","b":["[Tarrant County Medical Examiner]{.underline} findings and how they enter the case","How the claim converts and who may bring it","Why the medical record before death still drives the value"]},
   {"q":"How does a fall rather than a crash change a Tarrant County brain injury claim?","b":["[Premises Liability (Falls)]{.underline} as an alternate liability theory","Different defendant, different insurer, same medical proof problem","[Burden of Proof (Preponderance)]{.underline} applied to notice"]},
   {"q":"What mistakes most reduce the value of a Tarrant County brain injury claim?","b":["Gaps in treatment used to attack [Causation]{.underline}","Settling before [Maximum Medical Improvement]{.underline}","Recorded statements before anyone has documented the deficits"]},
  ]},
 ],
 "closing_q": "If somebody listening had a wreck a few months ago and has just been feeling off ever since, what do you want them to do?",
},

{
 "tab": "Slip and Fall (CA)",
 "emoji": "⚠️",
 "title": "Premises Liability, Duty of Care, and Proving Notice",
 "practice_area": "Slip and Fall",
 "scope_label": "CA - San Diego",
 "runtime": "~45 minutes (Interview ~25 min, Location Blocks ~13 min, Intro/Close ~7 min)",
 "ngram": "podcast/N-Gram Tables/Slip and Fall/Slip and Fall: Premises Liability, Duty of Care, and Proving Notice/Locations/CA - San Diego/n-gram-table.json",
 "emap": "podcast-research/slip-and-fall/locations/ca-san-diego/01-entities/entity-map.json",
 "jurisdiction": "California duty runs from [Civil Code Section 1714(a)]{.underline} and [Rowland v. Christian]{.underline} (1968), which abolished the rigid invitee/licensee/trespasser categories. The controlling notice case is [Ortega v. Kmart Corp.]{.underline} (2001), which allows constructive notice by length of time. Comparative fault is pure under [Li v. Yellow Cab]{.underline}. Jury instructions run [CACI 1000-1012]{.underline}. Statute of limitations is 2 years under [Code of Civil Procedure Section 335.1]{.underline}, but a public entity claim must be filed within 6 months under [Gov. Code Section 911.2]{.underline}, with liability under [Gov. Code Section 835]{.underline}. Venue is [San Diego County Superior Court]{.underline}.",
 "intro": "today we are getting into the case type everybody thinks is easy money and almost nobody wins without doing real work, which is the slip and fall.",
 "framing": "Roughly: falling on someone's property is not the case. Proving they knew about it, or should have, is the case. Almost everything turns on that one question.",
 "prompts": [
  {"t":"The misconception","q":"Slip and fall has a reputation. What do people assume when they call you, and how often is that assumption wrong?",
   "g":["[Premises Liability]{.underline} requires negligence, not just an injury on someone's property","[California Civil Code Section 1714(a)]{.underline} and the general duty of ordinary care","[Rowland v. Christian]{.underline} and why the old visitor categories no longer control","Falling is the easy fact. Everything after it is the case."],
   "f":["How many of these calls turn into cases?","What is the fastest way you know a call is not one?"]},
  {"t":"The whole case in one word","q":"If notice is the center of these cases, explain what that actually means in plain terms.",
   "g":["[Notice Doctrine]{.underline}: actual versus [Constructive Notice]{.underline}","[Ortega v. Kmart Corp.]{.underline} and constructive notice through length of time","How long a hazard sat there as the single most valuable fact","[Reasonable Care Standard]{.underline} and how long an owner gets to fix or warn"],
   "f":["How do you prove how long something was on the floor?","Is there a number of minutes that matters?"]},
  {"t":"Proving the thing nobody filmed","q":"How do you reconstruct a fall that took two seconds and that nobody was watching?",
   "g":["[Surveillance Footage]{.underline} and how fast it is overwritten","[Maintenance / Inspection Logs]{.underline} as the quiet best evidence in the case","[Incident Report]{.underline} and [Witness Statements]{.underline}","[Spoliation of Evidence]{.underline} and the preservation demand that has to go out immediately"],
   "f":["How quickly does footage disappear?","Have you had a case turn entirely on an inspection log?"],
   "story": True},
  {"t":"The blame-the-victim defense","q":"The other side's whole strategy seems to be that you should have been looking where you were going. How do you deal with that?",
   "g":["[Open and Obvious Doctrine]{.underline} as the primary defense","[Assumption of Risk]{.underline} and how [Knight v. Jewett]{.underline} merged secondary AoR into comparative fault","[Pure Comparative Negligence]{.underline} under [Li v. Yellow Cab]{.underline}: reduced, never barred","[CACI 1000-1012]{.underline} and how the jury is actually instructed"],
   "f":["Does partial fault kill these cases in practice?","How do you talk a client through being told it was their fault?"]},
  {"t":"Who owns the floor","q":"When you fall in a store, who are you actually dealing with? It seems like it is never just the store.",
   "g":["[Property Owner]{.underline} versus [Property Management Company]{.underline} versus [Maintenance / Cleaning Contractor]{.underline}","[Commercial General Liability (CGL) Policy]{.underline} and who tenders to whom","[California Building Standards Code (Title 24)]{.underline} violations and [ADA Compliance]{.underline} as independent theories","[Negligence Per Se]{.underline} where a code violation exists"],
   "f":["How long does it take to figure out who is responsible?","Do they point at each other?"]},
  {"t":"What it is worth","q":"These get dismissed as minor cases. When are they not?",
   "g":["[Fracture (Hip, Wrist, Ankle)]{.underline} as the common serious outcome","[Traumatic Brain Injury (TBI)]{.underline} and [Spinal Cord / Back Injury]{.underline} from a ground-level fall","[Economic Damages]{.underline} and [Non-Economic Damages]{.underline}","[Insurance Policy Limits]{.underline} and why the venue's coverage often exceeds expectations"],
   "f":["What is the most serious one you have handled?","What do people underestimate about a fall?"]},
 ],
 "blocks": [
  {"city":"San Diego","qs":[
   {"q":"Where do the most common San Diego slip and fall cases happen?","b":["[San Diego Major Retail / Commercial Venues]{.underline} including Westfield UTC, Fashion Valley, and Mission Valley","[Wet Floor Hazard]{.underline} and [Spilled Substance]{.underline} as the dominant mechanisms","[Parking Lot Defect]{.underline}, [Defective Stairs and Handrails]{.underline}, and [Uneven Flooring]{.underline}"]},
   {"q":"How do you prove a San Diego store knew about the hazard?","b":["[Constructive Notice]{.underline} under [Ortega v. Kmart Corp.]{.underline}","[Maintenance / Inspection Logs]{.underline} showing the sweep schedule and the gap in it","[Surveillance Footage]{.underline} demanded before the retention window closes"]},
   {"q":"Where do serious San Diego fall injuries get treated?","b":["[San Diego Trauma Center Network]{.underline}: Scripps Mercy, UC San Diego Health, Sharp Memorial, Rady Children's","Why a ground-level fall regularly produces a trauma activation","Continuous treatment as the causation record"]},
   {"q":"Does a San Diego police report exist for a slip and fall?","b":["[San Diego Police Department (SDPD)]{.underline} incident reports where one was generated","Why the store's own [Incident Report]{.underline} usually matters more","Getting a copy before you leave the property"]},
   {"q":"How long do you have to file a slip and fall claim in California?","b":["Two years under [Code of Civil Procedure Section 335.1]{.underline}","Six months for a government claim under [Gov. Code Section 911.2]{.underline}","Why the evidence deadline is far shorter than the filing deadline"]},
   {"q":"Which court hears a San Diego slip and fall lawsuit?","b":["[San Diego County Superior Court]{.underline} civil venue","How most resolve against a [Commercial General Liability (CGL) Policy]{.underline} before filing","What filing changes"]},
  ]},
  {"city":"Public property in San Diego","qs":[
   {"q":"Can the City of San Diego be liable for a fall on a sidewalk?","b":["[Dangerous Condition of Public Property]{.underline} under [Gov. Code Section 835]{.underline}","[San Diego City & County Public Premises]{.underline} risk management and self-insurance","What has to be shown that a private case does not require"]},
   {"q":"What is the six-month government claim deadline in San Diego?","b":["[California Government Claim Deadline]{.underline} under [Gov. Code Section 911.2]{.underline}","Miss it and the claim is over regardless of the two-year statute","Why this is the single most common way a public-property case dies"]},
   {"q":"How is a sidewalk fall different from a store fall in San Diego?","b":["[Government Entity]{.underline} defendant with a different claims path","Notice proven through complaint history and inspection records rather than sweep logs","Different timeline, different proof, same injury"]},
   {"q":"Does a building code violation help a San Diego public property case?","b":["[California Building Standards Code (Title 24)]{.underline} violations","[ADA Compliance]{.underline} failures on public premises","[Negligence Per Se]{.underline} where the violation caused the fall"]},
   {"q":"What evidence proves a dangerous condition existed on San Diego public property?","b":["Prior complaints and repair records held by the entity","[Witness Statements]{.underline} and photographs taken the same day","[Spoliation of Evidence]{.underline} demand directed at the entity"]},
   {"q":"What should you do this week after a fall on San Diego public property?","b":["Photograph the condition before it is repaired, because it will be","Start the [Gov. Code Section 911.2]{.underline} clock deliberately, not accidentally","Get treated and keep the record continuous"]},
  ]},
 ],
 "closing_q": "For someone who fell last week, is embarrassed about it, and is not sure it is worth anyone's time, what would you tell them?",
},
]
